AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: whisper-lambda-cpp

Globals:
  Function:
    Timeout: 3
    MemorySize: 128


Resources:
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub whisper-lambda-audio-${AWS::Region}-${AWS::AccountId}
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # WhisperCppLambdaFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Metadata:
  #     BuildMethod: makefile
  #   Properties:
  #     CodeUri: ./
  #     MemorySize: 10240
  #     Timeout: 300
  #     Handler: bootstrap
  #     Runtime: provided.al2023
  #     Architectures:
  #       - x86_64

  WhisperCppLambdaFunctionArm:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: ./
      MemorySize: 10240
      Timeout: 300
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
      Events:
        S3Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref AudioBucket
            InputTransformer:
              InputPathsMap:
                s3bucket: $.detail.bucket.name
                s3key: $.detail.object.key
              InputTemplate: '{"s3key": "<s3key>", "s3bucket": "<s3bucket>"}'
